import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { z } from 'zod';
const evidence = resolve('verification/windows-schema-live');
const { root, sourceId } = z.object({ root: z.string(), sourceId: z.string() }).parse(JSON.parse(readFileSync(join(evidence, 'run.json'), 'utf8')));
Object.assign(process.env, { MYCREW_HOME: root, WORKSPACE_ROOT: root, INGESTIGER_MODEL: 'claude-sonnet-5', INGESTIGER_PYTHON: 'C:/Users/user/AppData/Local/Python/pythoncore-3.14-64/python.exe' });
const { CorpusStore } = await import('../src/server/corpus/store.js');
const { WikiService } = await import('../src/server/wiki/service.js');
const { createWikiRoutes } = await import('../src/server/wiki/routes.js');
const { build } = await import('vite');
const { default: react } = await import('@vitejs/plugin-react');
const { Hono } = await import('hono');
const { serve } = await import('@hono/node-server');
const { serveStatic } = await import('@hono/node-server/serve-static');
const corpus = new CorpusStore(join(root, 'history/corpus'));
const ui = join(root, 'readonly-ui'); mkdirSync(ui, { recursive: true });
writeFileSync(join(ui, 'index.html'), '<!doctype html><html lang="ko"><meta charset="utf-8"><title>실제 협업 증거 · 읽기 전용 Wiki</title><div id="root"></div><script type="module" src="/main.tsx"></script></html>');
writeFileSync(join(ui, 'main.tsx'), `import React from 'react'; import {createRoot} from 'react-dom/client'; import {MantineProvider,Container,Alert} from '@mantine/core'; import '@mantine/core/styles.css'; import WikiPanel from ${JSON.stringify(resolve('src/client/components/Settings/WikiPanel.tsx'))}; const container=document.getElementById('root'); if(container)createRoot(container).render(<MantineProvider><Container size="lg" py="md"><Alert>읽기 전용 검증 화면: 실제 Sonnet/Opus 합성 협업 데이터. 기업 synthetic, 프로젝트 windows-collaboration. 추가 모델 호출과 수정 API는 차단됩니다.</Alert><WikiPanel snapshot={${JSON.stringify(corpus.snapshot(sourceId))}} close={()=>{}} /></Container></MantineProvider>);`);
await build({ configFile: false, root: ui, plugins: [react()], logLevel: 'warn', build: { outDir: join(ui, 'dist'), emptyOutDir: true } });
const app = new Hono();
app.use('/api/wiki/*', async (c, next) => c.req.method === 'GET' ? next() : c.json({ error: 'verification_readonly' }, 403));
app.route('/api/wiki', createWikiRoutes({ service: new WikiService(join(root, 'history/wiki'), corpus, () => true) }));
app.use('*', serveStatic({ root: join(ui, 'dist') }));
serve({ fetch: app.fetch, hostname: '127.0.0.1', port: 3490 });
writeFileSync(join(evidence, 'preview-server.json'), JSON.stringify({ pid: process.pid, port: 3490, root, readonly: true }));
console.log('Read-only real Wiki component: http://127.0.0.1:3490');
