/** Real Windows HTTP + stdio MCP, synthetic candidates only; no model calls. */
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { createHash } from 'node:crypto';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { Hono } from 'hono';
import { serve } from '@hono/node-server';
import { z } from 'zod';

const evidence = resolve('verification/windows-20260914');
mkdirSync(evidence, { recursive: true });
const root = mkdtempSync(join(evidence, '합성 협업 환경 '));
process.env.MYCREW_HOME = root;
process.env.WORKSPACE_ROOT = root;
mkdirSync(join(root, 'history'), { recursive: true });
writeFileSync(join(root, 'history/agents.json'), '{"agents":[]}');
const { CorpusStore } = await import('../src/server/corpus/store.js');
const { CorpusService } = await import('../src/server/corpus/service.js');
const { WikiService } = await import('../src/server/wiki/service.js');
const { WikiKnowledgeStore } = await import('../src/server/wiki/knowledge.js');
const { WikiWorkerService } = await import('../src/server/wiki/worker-service.js');
const { issueWikiWorkerAccess } = await import('../src/server/wiki/worker-access.js');
const { createWikiWorkerRoutes } = await import('../src/server/wiki/worker-routes.js');
const { createWikiRoutes } = await import('../src/server/wiki/routes.js');
const corpus = new CorpusStore(join(root, 'history/corpus'));
const importer = new CorpusService(corpus);
const wiki = new WikiService(join(root, 'history/wiki'), corpus, () => true);
const knowledge = new WikiKnowledgeStore(wiki);
const worker = new WikiWorkerService(knowledge);
const scope = { orgId: 'synthetic', projectId: 'windows-collaboration' };
const text = '2026-10-01부터 시스템은 주문 초안만 작성한다. 최종 주문은 사람이 실행한다. 자동 주문은 금지한다. 담당 부서는 아직 정하지 않았다.';
const sourceInput = { provider: 'local' as const, externalId: '합성 규정.md', name: '합성 규정.md', mime: 'text/markdown' };
const source = await importer.import({ ...sourceInput, bytes: Buffer.from(text) });
const units = corpus.snapshot(source.sourceId)?.units;
assert.ok(units?.length);
let job = await wiki.prepare({ scope, sourceId: source.sourceId, expectedRevision: source.revision, unitIds: units.map(unit => unit.id), model: 'synthetic-fixture-no-model' });
const request = job.payload.requests[0];
assert.ok(request);
job = await wiki.submit(job.id, { scope, response: { request_id: request.request_id, results: request.units.map(unit => ({ unit_id: unit.unit_id, status: 'analyzed', needs: [{ kind: 'constraint', title: '합성 주문 규정 전체', statement: text, details: [], departments: [], patterns: [], evidence: [unit.text], claim_status: 'source_reported' }] })) } });
const candidate = job.candidates[0];
const unit = request.units[0];
assert.ok(candidate && unit);
const reviewInput = { scope, jobId: job.id, candidateId: candidate.id, unitId: unit.unit_id, needIndex: 0, verdict: 'accept', reason: 'codex:synthetic-test: 합성 원문 전체와 대조. 실제 사람의 업무 승인이 아님.', conditionsChecked: true, baseSnapshot: null, knowledgeId: null, expectedRevision: null };
const first = await knowledge.commit(scope, knowledge.review(reviewInput, 'codex:synthetic-test').id);
const ref = { scope, id: first.knowledge.id, revision: 1 };
const access = { agent: 'analyst', jobId: 'synthetic-http-mcp', home: root, readPaths: ['/**'], sensitivePaths: [], canDelegate: true };
const grant = issueWikiWorkerAccess(access);
const app = new Hono();
app.route('/api/wiki-worker', createWikiWorkerRoutes({ service: worker, targetAccess: agent => ({ ...access, agent, readPaths: [] }), delegate: async () => { throw new Error('Denied recipient must never execute'); } }));
app.route('/api/wiki', createWikiRoutes({ service: wiki }));
const server = serve({ fetch: app.fetch, hostname: '127.0.0.1', port: 0 });
await new Promise<void>(done => server.listening ? done() : server.once('listening', done));
const address = server.address();
assert.ok(address && typeof address !== 'string');
const base = `http://127.0.0.1:${address.port}`;
const checks: string[] = [];
const outputPath = join(root, 'history/outputs/analyst/거래처 집계 보고서.md');
mkdirSync(join(root, 'history/outputs/analyst'), { recursive: true });
const bodySchema = z.object({ isError: z.boolean().optional(), content: z.array(z.object({ type: z.literal('text'), text: z.string() })) });
let citation = '';
try {
  for (let round = 0; round < 2; round++) {
    const client = new Client({ name: 'windows-surface-check', version: '1' });
    const transport = new StdioClientTransport({ command: process.execPath, args: ['--import', 'tsx', 'src/mcp/safefs-server.ts'], cwd: process.cwd(), stderr: 'pipe', env: { PATH: process.env.PATH ?? '', SystemRoot: process.env.SystemRoot ?? 'C:/Windows', TEMP: process.env.TEMP ?? root, MCP_MYCREW_HOME: root, MCP_SELF_DIR: process.cwd(), MCP_CWD: root, MCP_PROJECTS_DIR: root, MCP_AGENT_ROLE: 'analyst', MCP_READ_PATHS: '/**', MCP_WIKI_URL: `${base}/api/wiki-worker`, MCP_WIKI_TOKEN: grant.token } });
    try {
      await client.connect(transport);
      const names = (await client.listTools()).tools.map(tool => tool.name);
      for (const name of ['WikiSearch', 'WikiRead', 'WikiHandoff', 'WikiRecordUsage']) assert.ok(names.includes(name));
      const search = bodySchema.parse(await client.callTool({ name: 'WikiSearch', arguments: { scope, query: 'unrelated-query' } }));
      assert.equal(search.isError, false);
      const result = z.object({ items: z.array(z.unknown()), mandatory: z.array(z.object({ id: z.string() })) }).parse(JSON.parse(search.content[0].text));
      assert.equal(result.items.length, 0);
      assert.ok(result.mandatory.some(item => item.id === ref.id));
      const read = bodySchema.parse(await client.callTool({ name: 'WikiRead', arguments: ref }));
      assert.equal(read.isError, false);
      citation = z.object({ citation: z.string() }).parse(JSON.parse(read.content[0].text)).citation;
      const handoff = bodySchema.parse(await client.callTool({ name: 'WikiHandoff', arguments: { refs: [ref], agent: 'corpus-keeper', purpose: 'join_aggregate', request: 'vendor_code로 조인·집계' } }));
      assert.equal(handoff.isError, true);
      assert.match(handoff.content[0].text, /wiki_worker_scope_denied/);
      writeFileSync(outputPath, '인용 없는 결과');
      const absent = bodySchema.parse(await client.callTool({ name: 'WikiRecordUsage', arguments: { refs: [ref], outputPath } }));
      assert.equal(absent.isError, true);
      assert.match(absent.content[0].text, /wiki_citation_missing/);
      const master = [{ vendor_code: 'V001', vendor_name: '가상상사' }, { vendor_code: 'V002', vendor_name: '예시물산' }];
      const transactions = [{ vendor_code: 'V001', amount_krw: 1200 }, { vendor_code: 'V001', amount_krw: 800 }, { vendor_code: 'V002', amount_krw: 3000 }];
      const totals = master.map(vendor => ({ ...vendor, total: transactions.filter(row => row.vendor_code === vendor.vendor_code).reduce((sum, row) => sum + row.amount_krw, 0) }));
      assert.deepEqual(totals.map(row => row.total), [2000, 3000]);
      writeFileSync(outputPath, `# 합성 거래처 집계\n\n모델 직원이 작성한 보고서가 아닌 호스트 기능 검사입니다.\n\n${text} ${citation}\n\n${totals.map(row => `${row.vendor_code} ${row.vendor_name}: ${row.total}원`).join('\n')}\n합계: 5000원\n`);
      const saved = bodySchema.parse(await client.callTool({ name: 'WikiRecordUsage', arguments: { refs: [ref], outputPath } }));
      assert.equal(saved.isError, false);
      const receipt = z.object({ outputSha256: z.string(), locations: z.array(z.object({ lines: z.array(z.number()) })) }).parse(JSON.parse(saved.content[0].text));
      assert.equal(receipt.outputSha256, createHash('sha256').update(readFileSync(outputPath)).digest('hex'));
      assert.deepEqual(receipt.locations[0].lines, [5]);
      writeFileSync(join(root, `receipt-${round}.json`), saved.content[0].text);
      checks.push(`stdio MCP round ${round + 1}: registration/search/read/denied handoff/usage/hash/Korean paths`);
    } finally { await client.close(); }
  }
  for (const route of ['reviews', 'commit']) {
    const response = await fetch(`${base}/api/wiki/${route}`, { method: 'POST', headers: { Authorization: `Bearer ${grant.token}`, 'Content-Type': 'application/json' }, body: '{}' });
    assert.equal(response.status, 403);
  }
  checks.push('worker token cannot review or publish');
  writeFileSync(outputPath, `${readFileSync(outputPath, 'utf8')}\n기록 후 수정\n`);
  assert.equal(worker.usage(scope, ref.id).items[0].outputState, 'changed');
  const second = await knowledge.commit(scope, knowledge.review({ ...reviewInput, baseSnapshot: first.snapshot, knowledgeId: ref.id, expectedRevision: 1 }, 'codex:synthetic-test').id);
  assert.equal(second.knowledge.revision, 2);
  const staleHandoff = await fetch(`${base}/api/wiki-worker/handoff`, { method: 'POST', headers: { Authorization: `Bearer ${grant.token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ refs: [ref], agent: 'corpus-keeper', request: 'aggregate', purpose: 'join_aggregate' }) });
  assert.equal(staleHandoff.status, 409);
  assert.match(await staleHandoff.text(), /wiki_revision_changed/);
  assert.throws(() => worker.recordUsage(access, { refs: [ref], outputPath }), /wiki_revision_changed/);
  checks.push('revision change rejects stale handoff and usage; output modification detected');
  await importer.import({ ...sourceInput, bytes: Buffer.from(`${text}\n추가 규정: 재검토 필요`) });
  assert.equal(worker.read(access, { ...ref, revision: 2 }).sourceState, 'changed');
  assert.throws(() => worker.bundle(access, [{ ...ref, revision: 2 }]), /wiki_source_changed/);
  checks.push('original source change visible and application blocked');
  const report = { passed: true, realModel: false, realDelegation: false, ptyTested: false, platform: process.platform, root, sourceId: source.sourceId, jobId: job.id, ref, citation, outputPath, checks, usage: worker.usage(scope, ref.id) };
  writeFileSync(resolve('verification/windows-20260914/surface-result.json'), JSON.stringify(report, null, 2));
  console.log(JSON.stringify({ passed: true, checks, root, realModel: false }));
} finally { grant.revoke(); server.close(); }
process.exit(0);
