import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
const root = mkdtempSync(join(tmpdir(), 'wiki-json-response-'));
process.env.MYCREW_HOME = root;
process.env.WORKSPACE_ROOT = root;
mkdirSync(join(root, 'history'), { recursive: true });
writeFileSync(join(root, 'history/agents.json'), '{"agents":[]}');
const { CorpusStore } = await import('../src/server/corpus/store.js');
const { CorpusService } = await import('../src/server/corpus/service.js');
const { WikiService } = await import('../src/server/wiki/service.js');
const { WikiExecution, WIKI_MODEL } = await import('../src/server/wiki/execution.js');
const corpus = new CorpusStore(join(root, 'history/corpus'));
const source = await new CorpusService(corpus).import({ provider: 'local', externalId: 'rule.md', name: 'rule.md', mime: 'text/markdown', bytes: Buffer.from('자동 주문은 금지한다.') });
const units = corpus.snapshot(source.sourceId)?.units;
assert.ok(units?.length);
const wiki = new WikiService(join(root, 'history/wiki'), corpus, () => true);
const scope = { orgId: 'synthetic', projectId: 'fenced-response' };
const job = await wiki.prepare({ scope, sourceId: source.sourceId, expectedRevision: source.revision, unitIds: units.map(unit => unit.id), model: WIKI_MODEL });
const request = job.payload.requests[0];
const response = { request_id: request.request_id, results: request.units.map(unit => ({ unit_id: unit.unit_id, status: 'analyzed', needs: [{ kind: 'constraint', title: '주문 금지', statement: unit.text, details: [], evidence: [unit.text], departments: [], patterns: [], claim_status: 'source_reported' }] })) };
const execution = new WikiExecution(wiki, async () => ({ text: '```json\n' + JSON.stringify(response) + '\n```', model: WIKI_MODEL }));
const analyzed = await execution.analyze(job.id, { scope, requestId: request.request_id });
assert.equal(analyzed.job.candidates.length, 1);
console.log(JSON.stringify({ passed: true, fencedJsonAccepted: true, realModel: false }));
process.exit(0);
