import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { InMemoryTransport } from '@modelcontextprotocol/sdk/inMemory.js';
const root = mkdtempSync(join(tmpdir(), 'wiki-collaboration-'));
process.env.MYCREW_HOME = root; process.env.WORKSPACE_ROOT = root;
mkdirSync(join(root, 'history'), { recursive: true }); writeFileSync(join(root, 'history/agents.json'), '{"agents":[]}');
const { CorpusStore } = await import('../src/server/corpus/store.js');
const { CorpusService } = await import('../src/server/corpus/service.js');
const { WikiService } = await import('../src/server/wiki/service.js');
const { WikiKnowledgeStore } = await import('../src/server/wiki/knowledge.js');
const { WikiWorkerService, wikiCitation } = await import('../src/server/wiki/worker-service.js');
const { issueWikiWorkerAccess } = await import('../src/server/wiki/worker-access.js');
const { createWikiWorkerRoutes } = await import('../src/server/wiki/worker-routes.js');
const { registerWikiTools } = await import('../src/mcp/wiki-tools.js');
const { buildPermissionArgs } = await import('../src/agent.js');
let allowed = true;
const corpus = new CorpusStore(join(root, 'history/corpus'));
const importer = new CorpusService(corpus);
const wiki = new WikiService(join(root, 'history/wiki'), corpus, () => allowed);
const knowledge = new WikiKnowledgeStore(wiki);
const worker = new WikiWorkerService(knowledge);
const access = { agent: 'analyst', jobId: 'synthetic-job', home: root, readPaths: ['/**'], sensitivePaths: [], canDelegate: true };
const grant = issueWikiWorkerAccess(access);
const scope = { orgId: 'synthetic', projectId: 'workflow' };
const denied = (code: string) => (e: any) => e.code === code;
try {
  const source = await importer.import({ provider: 'local', externalId: 'order.md', name: 'order.md', mime: 'text/markdown', bytes: Buffer.from('자동 주문 금지. 사람이 최종 주문한다.') });
  let job = await wiki.prepare({ scope, sourceId: source.sourceId, expectedRevision: source.revision, unitIds: corpus.snapshot(source.sourceId)!.units!.map(u => u.id), model: 'synthetic' });
  const req = job.payload.requests[0];
  job = await wiki.submit(job.id, { scope, response: { request_id: req.request_id, results: req.units.map(u => ({ unit_id: u.unit_id, status: 'analyzed', needs: [{ kind: 'constraint', title: '주문 제한', statement: u.text, details: ['사람의 최종 주문'], evidence: [u.text], departments: [], patterns: [], claim_status: 'source_reported' }] })) } });
  const reviewInput = { scope, jobId: job.id, candidateId: job.candidates[0].id, unitId: req.units[0].unit_id, needIndex: 0, verdict: 'accept', reason: '합성 원문 대조', conditionsChecked: true, baseSnapshot: null, knowledgeId: null, expectedRevision: null };
  const first = await knowledge.commit(scope, knowledge.review(reviewInput, 'synthetic-reviewer').id);
  const ref = { scope, id: first.knowledge.id, revision: 1 };
  const search = worker.search(access, { scope, query: '관계없는 검색어', limit: 1 });
  assert.equal(search.items.length, 0); assert.equal(search.mandatory.length, 1);
  assert.throws(() => worker.search({ ...access, readPaths: ['/history/outputs/**'] }, { scope, query: '' }), denied('wiki_worker_scope_denied'));
  assert.throws(() => worker.search({ ...access, sensitivePaths: ['/history/wiki/**'] }, { scope, query: '' }), denied('wiki_worker_scope_denied'));
  assert.equal(worker.read(access, ref).citation, wikiCitation(ref));
  assert.throws(() => worker.read({ ...access, sensitivePaths: [`/history/corpus/${source.sourceId}/**`] }, ref), denied('wiki_worker_source_denied'));
  assert.throws(() => worker.read({ ...access, sensitivePaths: [`/history/wiki/organizations/synthetic/projects/workflow/snapshots/${first.snapshot}/knowledge/${ref.id}.md`] }, ref), denied('wiki_worker_source_denied'));
  const outputPath = join(root, 'history/outputs/analyst/report.md'); mkdirSync(join(root, 'history/outputs/analyst'), { recursive: true });
  writeFileSync(outputPath, '인용 없는 결과');
  assert.throws(() => worker.recordUsage(access, { refs: [ref], outputPath }), denied('wiki_citation_missing'));
  writeFileSync(outputPath, `자동 주문을 하지 않습니다. ${wikiCitation(ref)}`);
  const receipt = worker.recordUsage(access, { refs: [ref], outputPath });
  assert.deepEqual(receipt.locations[0].lines, [1]);
  assert.equal(receipt.verification, 'citation_present'); assert.equal(receipt.semanticApplication, 'not_evaluated');
  assert.deepEqual(worker.recordUsage(access, { refs: [ref], outputPath }), receipt);
  assert.equal(worker.usage(scope, ref.id).items[0].outputState, 'unchanged');
  writeFileSync(outputPath, '수정한 결과');
  assert.equal(worker.usage(scope, ref.id).items[0].outputState, 'changed');
  let delegated = 0; let request = '';
  const app = createWikiWorkerRoutes({ service: worker, targetAccess: agent => ({ ...access, agent }), delegate: async input => { delegated++; request = input.request; return { jobId: 'child-job' }; } });
  const post = (path: string, data: unknown, token = grant.token) => app.request(`http://localhost${path}`, { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify(data) });
  assert.equal((await post('/read', ref, 'invalid')).status, 403);
  assert.equal((await app.request('http://localhost/read', { method: 'POST', headers: { Authorization: `Bearer ${grant.token}`, Origin: 'http://localhost' }, body: JSON.stringify(ref) })).status, 403);
  const handoff = { refs: [ref], agent: 'corpus-keeper', request: '거래표를 조인해 주세요', purpose: 'join_aggregate' };
  assert.equal((await post('/handoff', { ...handoff, purpose: 'analysis' })).status, 400);
  const noDelegate = issueWikiWorkerAccess({ ...access, canDelegate: false });
  assert.equal((await post('/handoff', handoff, noDelegate.token)).status, 403); noDelegate.revoke();
  const restrictedApp = createWikiWorkerRoutes({ service: worker, targetAccess: agent => ({ ...access, agent, readPaths: [] }), delegate: async () => { throw new Error('must not delegate'); } });
  assert.equal((await restrictedApp.request('http://localhost/handoff', { method: 'POST', headers: { Authorization: `Bearer ${grant.token}`, 'Content-Type': 'application/json' }, body: JSON.stringify(handoff) })).status, 403);
  assert.equal((await post('/handoff', handoff)).status, 200); assert.equal((await post('/handoff', handoff)).status, 200);
  assert.equal(delegated, 1); assert.ok(request.includes('자동 주문 금지')); assert.ok(request.includes(wikiCitation(ref)));
  // Exercise MCP registration and JSON transport end to end without an external model.
  const realFetch = globalThis.fetch;
  globalThis.fetch = (async (url, init) => app.request(String(url), init)) as typeof fetch;
  const server = new McpServer({ name: 'synthetic', version: '1' });
  const client = new Client({ name: 'test', version: '1' });
  const [a,b] = InMemoryTransport.createLinkedPair();
  try {
    registerWikiTools(server, 'http://localhost', grant.token);
    await server.connect(a); await client.connect(b);
    assert.equal((await client.listTools()).tools.length, 4);
    const result = await client.callTool({ name: 'WikiRead', arguments: ref });
    assert.ok(JSON.stringify(result).includes('자동 주문 금지')); assert.ok(!result.isError);
  } finally { await client.close(); await server.close(); globalThis.fetch = realFetch; }
  const second = await knowledge.commit(scope, knowledge.review({ ...reviewInput, baseSnapshot: first.snapshot, knowledgeId: ref.id, expectedRevision: 1 }, 'synthetic-reviewer').id);
  assert.equal(second.knowledge.revision, 2);
  assert.equal(worker.usage(scope, ref.id).items[0].knowledgeState, 'revised');
  assert.throws(() => worker.bundle(access, [ref]), denied('wiki_revision_changed'));
  allowed = false;
  assert.throws(() => worker.read(access, { ...ref, revision: 2 }), denied('wiki_source_unavailable'));
  allowed = true;
  await importer.import({ provider: 'local', externalId: 'order.md', name: 'order.md', mime: 'text/markdown', bytes: Buffer.from('변경된 주문 규칙') });
  assert.throws(() => worker.bundle(access, [{ ...ref, revision: 2 }]), denied('wiki_source_changed'));
  const { createServerApp } = await import('../src/server/create-server-app.js');
  const mounted = createServerApp();
  const mountedRead = await mounted.request('http://localhost/api/wiki-worker/read', { method: 'POST', headers: { Authorization: `Bearer ${grant.token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ ...ref, revision: 2 }) });
  assert.equal(mountedRead.status, 200);
  assert.equal((await mounted.request('http://localhost/api/wiki-worker/read', { method: 'POST', body: JSON.stringify(ref) })).status, 403);
  assert.equal((await mounted.request('http://localhost/api/wiki/reviews', { method: 'POST', body: '{}' })).status, 403);
  grant.revoke(); assert.equal((await post('/read', ref)).status, 403);
  const permissionArgs = buildPermissionArgs({ role: 'analyst', name: 'test', allowedTools: ['DelegateTask'], readPaths: ['/**'], maxTurns: 1, systemPrompt: '' } as any).join(' ');
  for (const tool of ['WikiSearch', 'WikiRead', 'WikiRecordUsage', 'WikiHandoff']) assert.ok(permissionArgs.includes(`mcp__safefs__${tool}`));
  console.log(JSON.stringify({ passed: true, checks: ['mandatory outside ranking', 'scope and sensitive path denial', 'citation readback and idempotency', 'output changed', 'capability authentication and revocation', 'recipient permission', 'conditional handoff and dedup', 'MCP transport', 'knowledge revision impact', 'revoked and changed source', 'worker allowlist'], realModel: false }));
} finally { grant.revoke(); rmSync(root, { recursive: true, force: true }); }

process.exit(0); // Host module background timers are not part of this isolated test.
